'use client'

import { Copy, Download, FilePlus2, Menu, Pencil, Save, Trash2, Upload, X } from 'lucide-react'
import dynamic from 'next/dynamic'
import { useCallback, useEffect, useRef, useState } from 'react'
import type { Editor } from 'tldraw'
import { db, isQuotaError } from '@/lib/db'
import { newBoard, type LocalBoard, type SaveState } from '@/lib/models'
import './create.css'

const Canvas=dynamic(()=>import('./tldraw-canvas'),{ssr:false,loading:()=> <div className="center-state"><div className="spinner"/><p>Loading the infinite canvas…</p></div>})
const download=(name:string,value:unknown)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export default function CreativeWorkspace(){
 const [boards,setBoards]=useState<LocalBoard[]>([]),[activeId,setActiveId]=useState(''),[loading,setLoading]=useState(true),[panel,setPanel]=useState(true),[save,setSave]=useState<SaveState>('idle'),[notice,setNotice]=useState<{text:string;error?:boolean}|null>(null);const editorRef=useRef<Editor|null>(null),fileRef=useRef<HTMLInputElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null)
 const active=boards.find(b=>b.id===activeId)
 const refresh=useCallback(async(id?:string)=>{const all=await db.boards.orderBy('updatedAt').reverse().toArray();setBoards(all);const wanted=id||localStorage.getItem('my-space:last-board')||all[0]?.id;if(wanted)setActiveId(all.some(b=>b.id===wanted)?wanted:all[0]?.id)},[])
 useEffect(()=>{void(async()=>{try{let all=await db.boards.toArray();if(!all.length){const first=newBoard('Ideas board');await db.boards.add(first);all=[first]}await refresh()}catch{setNotice({text:'Canvas storage is unavailable. You can draw, but export before leaving.',error:true})}finally{setLoading(false)}})()},[refresh])
 useEffect(()=>{if(activeId)localStorage.setItem('my-space:last-board',activeId)},[activeId])
 const create=async()=>{const b=newBoard();await db.boards.add(b);await refresh(b.id)}
 const rename=async(b:LocalBoard)=>{const title=prompt('Board name',b.title)?.trim();if(!title)return;await db.boards.update(b.id,{title,updatedAt:new Date().toISOString()});await refresh(b.id)}
 const duplicate=async(b:LocalBoard)=>{const copy={...b,id:crypto.randomUUID(),title:`${b.title} copy`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await db.boards.add(copy);await refresh(copy.id)}
 const remove=async(b:LocalBoard)=>{if(!confirm(`Delete “${b.title}”? This cannot be undone.`))return;await db.boards.delete(b.id);const rest=boards.filter(x=>x.id!==b.id);if(!rest.length){const fresh=newBoard();await db.boards.add(fresh);await refresh(fresh.id)}else await refresh(rest[0].id)}
 const changed=(snapshot:unknown)=>{if(!activeId)return;setSave('saving');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(async()=>{try{const updatedAt=new Date().toISOString();await db.boards.update(activeId,{snapshot,updatedAt});setBoards(v=>v.map(b=>b.id===activeId?{...b,snapshot,updatedAt}:b));setSave('saved')}catch(err){setSave('error');setNotice({text:isQuotaError(err)?'Browser storage is full. Export this board now; the canvas remains open.':'The board could not be saved. Export it before leaving.',error:true})}},900)}
 const importBoard=async(file?:File)=>{if(!file)return;try{const data=JSON.parse(await file.text()) as {format?:string;snapshot?:unknown;title?:string};const snapshot=data.format==='my-space-board'?data.snapshot:data;if(!snapshot||typeof snapshot!=='object')throw new Error();const b=newBoard(data.title||file.name.replace(/\.[^.]+$/,''));b.snapshot=snapshot;await db.boards.add(b);await refresh(b.id);setNotice({text:'Board imported.'})}catch{setNotice({text:'This is not a valid board snapshot.',error:true})}finally{if(fileRef.current)fileRef.current.value=''}}
 if(loading)return <div className="center-state"><div className="spinner"/><p>Restoring boards…</p></div>
 return <div className="creative"><aside className={`board-panel ${panel?'':'closed'}`}><div className="board-heading"><div><span className="eyebrow">Creative mode</span><h1>Boards</h1></div><button className="icon-button" onClick={create} aria-label="New board"><FilePlus2/></button></div><div className="board-list">{boards.map(b=><button key={b.id} className={`board-row ${b.id===activeId?'active':''}`} onClick={()=>setActiveId(b.id)}><span className="board-preview">{b.snapshot?<Pencil/>:<span>+</span>}</span><span className="board-copy"><strong>{b.title}</strong><small>{new Date(b.updatedAt).toLocaleDateString()}</small></span><span className="board-actions" onClick={e=>e.stopPropagation()}><span role="button" tabIndex={0} onClick={()=>void rename(b)} title="Rename"><Pencil/></span><span role="button" tabIndex={0} onClick={()=>void duplicate(b)} title="Duplicate"><Copy/></span><span role="button" tabIndex={0} onClick={()=>void remove(b)} title="Delete"><Trash2/></span></span></button>)}</div><div className="board-footer"><button className="button" onClick={()=>fileRef.current?.click()}><Upload/>Import board</button><button className="button" onClick={()=>active&&download(`${active.title}.tldr.json`,{format:'my-space-board',version:1,title:active.title,snapshot:active.snapshot})}><Download/>Export JSON</button><input ref={fileRef} className="sr-only" type="file" accept=".json,.tldr" onChange={e=>void importBoard(e.target.files?.[0])}/><p>Changes stay on this device. Use tldraw&apos;s menu to export PNG or SVG.</p></div></aside>
  <section className="canvas-area"><header className="canvas-header"><button className="icon-button" onClick={()=>setPanel(v=>!v)} aria-label="Toggle boards"><Menu/></button><strong>{active?.title}</strong><div className="save-state" data-state={save}><span className="dot"/>{save==='saving'?'Saving…':save==='error'?'Save failed':'Saved locally'}</div></header><div className="canvas-wrap">{active&&<Canvas key={active.id} snapshot={active.snapshot} onEditor={e=>editorRef.current=e} onChange={changed}/>}</div></section>
  {notice&&<div className={`toast ${notice.error?'error':''}`} role="status">{notice.text}<button className="icon-button" onClick={()=>setNotice(null)} aria-label="Dismiss"><X/></button>{notice.error&&active&&<button className="button" onClick={()=>download(`${active.title}.json`,active.snapshot)}><Save/>Export now</button>}</div>}
 </div>
}
